CPB: false
PCB: false
angle: false
arc: false
balance: false
batchsize: 48
color_jitter: false
data_dir: ./data/pytorch_VeRi
droprate: 0.0
erasing_p: 0.5
fp16: false
gpu_ids:
- 0
- 1
- 2
h: 299
init_name: imagenet
inputsize: 256
lr: 0.02
name: Res50_imbalance_s1_256_p0.5_lr2_mt_d0_b48
nclasses: 31605
pool: avg
resume: false
stride: 1
train_all: false
train_comp: false
train_comp_veri: false
train_cycle: true
train_milktea: false
train_pku: false
train_veri: false
use_DSE: false
use_IR: false
use_NAS: false
use_SE: false
use_dense: false
w: 299
